Feat/prepare for dev
bamboooo-dev/himo-ingame pull request #1
Opened 2021-02-14 12:48 UTC by yamagai

やっとこ開発の準備整いました

2021-02-15 03:13 UTC, MONAKA0721 requested changes

2021-02-15 03:13 UTC, MONAKA0721 commented on Dockerfile
> +ENV TZ Asia/Tokyo
tzdata 入れないと TZ 反映されないからもし反映させたいなら入れといて
(outgame も入れ忘れてたけど)

まあビルドステージで必要なんかってのもある

2021-02-15 03:13 UTC, MONAKA0721 commented on nginx/default.conf
> +  # }
ここはまだってこと？

2021-02-16 13:15 UTC, yamagai commented on Dockerfile
> +ENV TZ Asia/Tokyo
いらんな、消しとく

2021-02-16 13:16 UTC, yamagai commented on nginx/default.conf
> +  # }
あーそう、まだ pub/sub の詳しい仕様決まってないからデフォルトで書いてたのは消さずに残した感じ

2021-02-16 15:33 UTC, MONAKA0721 approved these changes

2021-02-17 17:56 UTC, merged