ingame 実装
bamboooo-dev/himo-ingame pull request #2
Opened 2021-03-03 17:30 UTC by yamagai

2021-03-04 16:03 UTC, MONAKA0721 requested changes

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/usecase/repository/himo/room_theme_repository.go
> +	Create(db *gorp.DbMap, roomID int, themeIDs []int) ([]model.RoomTheme, error)
引数、room と theme にしてほしい

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/usecase/repository/himo/room_repository.go
> +	Create(db *gorp.DbMap, max int, channelName string) (model.Room, error)
引数 room

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/usecase/interactor/create_room_interactor.go
> +	}
もし roomService を作るなら、`roomThemeRepo.Create` もその中でしてほしいかな

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/usecase/interactor/create_room_interactor.go
> +	}
一連の処理やと思うし

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/interface/mysql/himo/room_theme_repository_mysql.go
> +		// TODO: N+1 なってるからバルクインサートするようにしたい
目をつむります

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/interface/handler/room.go
> +	randomString := string(b)
ここは interactor ちゃうかな？
Handler はあくまでリクエストを処理して、レスポンスを整形して返すってイメージ

2021-03-04 16:03 UTC, MONAKA0721 commented on internal/domain/model/room_theme.go
> +}
これやっちゃうとデータ指向って感じやな
部屋が絶対お題持ってるなら

```
type Room struct {
   ...
   themes []Theme
}
```
にしてほしい

2021-03-07 11:18 UTC, yamagai commented on internal/interface/mysql/himo/room_theme_repository_mysql.go
> +		// TODO: N+1 なってるからバルクインサートするようにしたい
後々やります

2021-03-07 11:18 UTC, yamagai commented on internal/usecase/interactor/create_room_interactor.go
> +	}
なるほど、対応しやした

2021-03-07 11:45 UTC, yamagai commented on internal/usecase/repository/himo/room_repository.go
> +	Create(db *gorp.DbMap, max int, channelName string) (model.Room, error)
Room の Create で引数 room は無理じゃないです？
とりあえず Room model に `themes []Theme` 追加したからそれに合わせて変えた

2021-03-07 11:58 UTC, yamagai commented on internal/usecase/repository/himo/room_theme_repository.go
> +	Create(db *gorp.DbMap, roomID int, themeIDs []int) ([]model.RoomTheme, error)
`model.Room` に Themes 持たせたから room だけ渡すようにしました
この Create の前に theme 取り出して引数に渡した方がいいとかあれば教えて

2021-03-07 12:01 UTC, yamagai commented on internal/interface/handler/room.go
> +	randomString := string(b)
あー確かに
ランダム文字列作る責務は interactor に持たせるようにしました

2021-03-07 12:44 UTC, yamagai commented on internal/domain/model/room_theme.go
> +}
```
type Room struct {
   ...
   themes []Theme
}
```
にしました

2021-03-07 12:49 UTC, yamagai commented
roomService の処理の流れは↓
`roomRepo.Create`で渡された themeIDs をもとに room 作って`model.Room` 返す、
返ってきた `model.Room` を元に `roomThemeRepo.Create`で room_themes にデータ入れる

2021-03-08 12:43 UTC, MONAKA0721 commented on internal/usecase/repository/himo/room_theme_repository.go
> +	Create(db *gorp.DbMap, roomID int, themeIDs []int) ([]model.RoomTheme, error)
これ `BulkCreate` やんな？
BulkCreate(rooms, themes)にしてほしいな

2021-03-08 12:45 UTC, MONAKA0721 commented on internal/usecase/repository/himo/room_repository.go
> +	Create(db *gorp.DbMap, max int, channelName string) (model.Room, error)
無理ちゃうと思う
こういうところでドメインモデル使わないとリポジトリがロジック持っちゃって DDD の良さ消える気がする

2021-03-08 12:49 UTC, MONAKA0721 commented on internal/domain/model/room_theme.go
> +}
`room_theme.go` は いらないなら消して

2021-03-08 12:57 UTC, MONAKA0721 requested changes
`roomService.Create` は
```
themes = ThemeRepo.FetchByIDs(themeIDs)
room = model.Room{
   themes: themes
}
RoomRepo.Create(room)
RoomThemeRepo.BulkCreate(room, themes)
```
ってのをイメージしてるけどどうかな？
リポジトリはあくまで DB 操作であって欲しい気がする
ドメインにロジックをやっぱ持たせたいから

意見とかあるなら議論しよう

2021-03-08 15:55 UTC, yamagai commented on internal/usecase/repository/himo/room_repository.go
> +	Create(db *gorp.DbMap, max int, channelName string) (model.Room, error)
あー理解したかも
なんかずっと引数同じの回してるだけでよくない気がしてたけどリポジトリにロジック持たせてるからか、でそうじゃないと DDD の意味ないのもなんとなくわかる

2021-03-08 16:27 UTC, yamagai commented
> `roomService.Create` は
> 
> ```
> themes = ThemeRepo.FetchByIDs(themeIDs)
> room = model.Room{
>    themes: themes
> }
> RoomRepo.Create(room)
> RoomThemeRepo.BulkCreate(room, themes)
> ```
> 
> ってのをイメージしてるけどどうかな？
> リポジトリはあくまで DB 操作であって欲しい気がする
> ドメインにロジックをやっぱ持たせたいから
> 
> 意見とかあるなら議論しよう



> `roomService.Create` は
> 
> ```
> themes = ThemeRepo.FetchByIDs(themeIDs)
> room = model.Room{
>    themes: themes
> }
> RoomRepo.Create(room)
> RoomThemeRepo.BulkCreate(room, themes)
> ```
> 
> ってのをイメージしてるけどどうかな？
> リポジトリはあくまで DB 操作であって欲しい気がする
> ドメインにロジックをやっぱ持たせたいから
> 
> 意見とかあるなら議論しよう

なんの反論もない、そういうことかって感じですう

2021-03-08 16:29 UTC, yamagai commented on internal/domain/model/room_theme.go
> +}
`oomThemeRepo.BulkCreate` の返り値に使っていたものの、その返り値どこにも使わんので Create の返り値を err だけにして削除した

2021-03-08 16:30 UTC, yamagai commented on internal/usecase/repository/himo/room_theme_repository.go
> +	Create(db *gorp.DbMap, roomID int, themeIDs []int) ([]model.RoomTheme, error)
対応しました

2021-03-08 17:11 UTC, MONAKA0721 approved these changes
LGTM!!

2021-03-08 17:14 UTC, merged